services:
  - type: web
    name: asset-inventory-backend
    env: python
    pythonVersion: "3.12.7"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: FLASK_ENV
        value: production